# Workflow name
name: frontend-cd

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Use Latest NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci

    - name: Checkout Run Lint
      run: cd starter/frontend && npm run lint

  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Use Latest NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Install Dependencies
      working-directory: starter/frontend
      run: npm ci
  
    - name: Test
      run: cd starter/frontend && npm run test

  build:
    needs: [Linting, Test]
    runs-on: ubuntu-latest

    steps:
    - name: Check the Repository
      uses: actions/checkout@v4

    - name: Use Latest NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'
        cache: 'npm'
        cache-dependency-path: starter/frontend/package-lock.json

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to AWS 
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker Image
      working-directory: starter/frontend
      env:
        REPO_NAME: frontend
      run: |
        docker build --build-arg=REACT_APP_MOVIE_API_URL="http://localhost:5000" --tag 533174523052.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:${GITHUB_SHA::7} .
        docker push 533174523052.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:${GITHUB_SHA::7}

    - name: Configure Kubeconfig
      run: aws eks update-kubeconfig --name cluster --region us-east-1
       
    - name: Deploy Docker Image to Amazon EKS
      working-directory: starter/frontend/k8s
      env:
        IMAGE_TAG: latest
        REPO_NAME: frontend
      run: |
          aws eks update-kubeconfig --name cluster --region us-east-1
          kustomize edit set image frontend=533174523052.dkr.ecr.us-east-1.amazonaws.com/$REPO_NAME:${GITHUB_SHA::7}
          kustomize build . | kubectl apply -f - --validate=false
